# Generated by Django 3.2.4 on 2021-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
