# Generated by Django 3.2.4 on 2021-06-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('cpf', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbeiro_agendado', to='barbers.barber')),
            ],
        ),
    ]
